### ISSUE TITLE
[Feature Request] Provide array of color options to choose from

### ISSUE THREAD

**Issue by lanrat** [BoD/android-wear-color-picker#3] opened 2019-02-03 23:38 UTC
Would it be possible to provide an option to provide the ColorPickActivity with a list/array of colors to choose from? For my specific use-case I'd like to show show only [material colors](https://www.materialui.co/colors).

Thanks for creating this great library!

**Comment by BoD** [comment] 2019-02-16 21:09
Version 2.2.0 that was just published is tackling this request.  I hope you'll find it matches your use case!  If not, please don't hesitate to tell me.

**Comment by lancelinksp** [comment] 2019-03-28 03:12
First off, thank you for the great library. I was using 1.0.1 until just now I am trying to use 2.2.0 and every time I click on my button to open the 'Rainbow' color picker it force closes and debugging throws the following
`2019-03-27 23:03:48.131 21593-21593/com.lancelinksp.framed E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.lancelinksp.framed, PID: 21593
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/databinding/DataBinderMapperImpl;
        at android.databinding.DataBindingUtil.<clinit>(DataBindingUtil.java:32)
        at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284)
        at org.jraf.android.androidwearcolorpicker.ColorPickActivity.onCreate(ColorPickActivity.kt:68)
        at android.app.Activity.performCreate(Activity.java:6682)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.databinding.DataBinderMapperImpl" on path: DexPathList[[zip file "/system/framework/com.google.android.wearable.jar", zip file "/data/app/com.lancelinksp.framed-1/base.apk"],nativeLibraryDirectories=[/data/app/com.lancelinksp.framed-1/lib/arm, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.databinding.DataBindingUtil.<clinit>(DataBindingUtil.java:32) 
        at android.databinding.DataBindingUtil.setContentView(DataBindingUtil.java:284) 
        at org.jraf.android.androidwearcolorpicker.ColorPickActivity.onCreate(ColorPickActivity.kt:68) 
        at android.app.Activity.performCreate(Activity.java:6682) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

Any thought on what I could be doing wrong? Or is this a problem with the ColorPickActivity line 68?
Any help you could provide would be greatly appreciated

**Comment by BoD** [comment] 2019-03-28 06:10
@lancelinksp could open a different issue for this please?

**Comment by lancelinksp** [comment] 2019-03-28 09:27
@BoD sorry, shortly after commenting I figured it out. Had to have 
'dataBinding { enabled = true } in my build.gradle

**Comment by BoD** [comment] 2019-09-07 15:33
Closing now since this was addressed by v2.2.0

**Closed as completed by BoD** 2019-09-07 15:33 UTC
